### PR TITLE
 added equal sum partition problem

### PR DESCRIPTION
**Pull request by purnima11-igdtu**

### CODE REVIEW

**Comment by TheFenrisLycaon** [comment]
Please create an issue first. Then add your code with reference to that issue. 

Read the docs for more info.

Closing this.

**Comment by purnima11-igdtu** [comment]
can u plz assign me

**Comment by TheFenrisLycaon** [comment]
@purnima11-igdtu You need to create an issue. Only then I can assign you.

**Comment by purnima11-igdtu** [comment]
can you please provide me the steps to create the issue.

**Comment by TheFenrisLycaon** [comment]
Read contributing.md

**Pull request closed without merging**
