### PR TITLE
Added Depth First Search Algorithm

### PR DESCRIPTION
**Pull request by iMohitPant**
Added Depth First Search Algorithm code written in CPP.
Time complexity: O(V + E), where V is the number of vertices and E is the number of edges in the graph.
Space Complexity: O(V). 
Since an extra visited array is needed of size V.

### CODE REVIEW

**Comment by TheFenrisLycaon** [comment]
Please add a reference to the issue you created. Your code seems okay. :)

**Comment by iMohitPant** [comment]
#3

**Comment by iMohitPant** [comment]
reference to issue #9

**Review by TheFenrisLycaon — APPROVED** [review]
Perfect. :)

**Pull request merged**
